name: Run Telegram Bot

on:
  workflow_dispatch:  # allows manual run

jobs:
  run-telegram-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run the bot
      env:
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        ALLOWED_CHAT_ID: ${{ secrets.ALLOWED_CHAT_ID }}
      run: |
        python "T_api+cleaned.py"
